name: Trivy
on:
  pull_request:
  workflow_dispatch:
jobs:
  determine-changes:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ./packages/sub1: packages/sub1/**
            ./packages/sub2: packages/sub2/**
            ./Gemfile.lock: Gemfile.lock
            ./package-lock.json: package-lock.json

  scan:
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.packages != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.determine-changes.outputs.packages) }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          exit-code: 1
          format: table
          hide-progress: true
          ignore-unfixed: true
          scan-ref: ${{ matrix.package }}
          scan-type: fs
          severity: HIGH,CRITICAL
          trivyignores: .github/.trivyignore
          vuln-type: library
  status:
    needs: scan
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - name: Trivy Succeeded
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Trivy Failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1