name: Trivy New
on:
    pull_request:
        paths:
            - .github/workflows/trivy.yml
    workflow_dispatch:

permissions: write-all
jobs:
    changes:
      runs-on: ubuntu-22.04
      outputs:
        # Expose matched filters as job 'packages' output variable
        packages: ${{ steps.filter.outputs.changes }}
      steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            package1: packages/sub1/**
            package2: packages/sub2/**

    trivy-job:
        runs-on: ubuntu-22.04
        needs: changes
        strategy:
          matrix:
            package: ${{ fromJSON(needs.changes.outputs.packages) }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.20.0
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: table
                # exit-code: 1
                hide-progress: true
                scan-ref: ./packages/${{ matrix.package }}