name: Trivy New
on:
    pull_request:
        paths:
            - .github/workflows/trivy.yml
    workflow_dispatch:

permissions: write-all
jobs:
    determine-changes:
      runs-on: ubuntu-22.04
      outputs:
        # Expose matched filters as job 'packages' output variable
        changed_directories: ${{ steps.set-output.outputs.changed_directories }}
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v35
          with:
            dir_names: true
            dir_names_max_depth: 2  # This is optional. If not provided, full subdirectories' paths will be provided. Use it if you need to trim the output. See docs for details: https://github.com/tj-actions/changed-files/tree/main#inputs.
            json: true
            quotepath: false

        - name: 'Set output in the matrix format'
          id: set-output
          run: echo "changed_directories={\"dir\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

    trivy-job:
        runs-on: ubuntu-22.04
        if: ${{ needs.determine-changes.outputs.changed_directories != '' }}
        needs: determine-changes
        strategy:
          matrix:
            package: ${{ fromJSON(needs.determine-changes.outputs.changed_directories) }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.20.0
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: table
                # exit-code: 1
                hide-progress: true
                scan-ref: ./packages/${{ matrix.package }}